apiVersion: lukemcewen.com/v1
kind: ShopifyScraper
metadata:
  labels:
    app.kubernetes.io/name: shopify-crd
    app.kubernetes.io/managed-by: kustomize
  name: shopifyscraper-sample
spec:
  name: shopifyscraper-sample
  url: store.example.com  #SHOPIFY STORE DOMAIN
  watchtime: 60           #TIME IN SECONDS